### ISSUE TITLE
Positioning of Shuffled Pieces

### ISSUE THREAD

**Issue by naveenshaji** [jfmdev/jqJigsawPuzzle#1]
Is there any way in which the pieces when shuffled, are outside the canvas, lined up on the side, waiting to be dragged and dropped, because right now, for larger images there is a huge mess on the canvas. 

Also, is there any way this could be responsive?

**Comment by jfmdev** [comment]
Hi Naveen,

The library only supports to define the area in which the pieces are shuffled (by default they are shuffled inside the puzzle's frame) by setting the properties `rightLimit`, `leftLimit`, `topLimit` and `bottomLimit` (in the parameter `options.shuffle`).

However you can modify this behavior by changing the method `shufflePieces()`.

Regarding for the responsiveness, I'm not sure how could it be implemented.

Best regards and sorry for the late response.
